/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CheatItem {
  'id' : string,
  'creditCost' : bigint,
  'name' : string,
  'description' : string,
  'dailyLimit' : bigint,
}
export type CooldownArray = Array<[string, Time]>;
export interface CustomTaskWithStatus {
  'id' : string,
  'title' : string,
  'completed' : boolean,
  'attributePoints' : bigint,
  'points' : bigint,
}
export interface DailyTask {
  'id' : string,
  'xpReward' : bigint,
  'description' : string,
  'coinReward' : bigint,
}
export interface DailyTaskRecommendation {
  'incomplete' : Array<DailyTask>,
  'completed' : Array<DailyTask>,
}
export interface DamageResult { 'damage' : bigint, 'stats' : Array<bigint> }
export interface DisciplineSkill {
  'id' : string,
  'requiredLevel' : bigint,
  'name' : string,
  'description' : string,
}
export interface LeaderboardEntry {
  'principal' : Principal,
  'nickname' : string,
  'level' : bigint,
  'avatarChoice' : string,
}
export interface Mission {
  'id' : string,
  'missionType' : { 'repeatable' : null } |
    { 'daily' : null },
  'xpReward' : bigint,
  'name' : string,
  'description' : string,
  'coinReward' : bigint,
}
export interface Mob {
  'name' : string,
  'level' : bigint,
  'typeIndex' : bigint,
  'stats' : StatArray,
}
export type PurchaseResult = { 'dailyLimitReached' : null } |
  { 'itemNotFound' : null } |
  { 'success' : null } |
  { 'unauthorized' : null } |
  { 'insufficientCredits' : null };
export type QuestionnaireAnswers = Array<string>;
export interface Skill {
  'id' : string,
  'name' : string,
  'description' : string,
  'requirements' : SkillRequirements,
}
export interface SkillRequirements {
  'minLevel' : bigint,
  'minStats' : Array<[bigint, bigint]>,
}
export type StatArray = Array<bigint>;
export type StatNameArray = Array<string>;
export type Time = bigint;
export interface UserMission {
  'id' : string,
  'missionType' : { 'repeatable' : null } |
    { 'daily' : null },
  'xpReward' : bigint,
  'name' : string,
  'createdBy' : Principal,
  'description' : string,
  'coinReward' : bigint,
}
export interface UserProfile {
  'xp' : bigint,
  'credits' : bigint,
  'nickname' : string,
  'inventory' : Array<string>,
  'coins' : bigint,
  'unspentStatPoints' : bigint,
  'completedMissions' : Array<string>,
  'completedDailyTasks' : Array<string>,
  'level' : bigint,
  'stats' : StatArray,
  'questionnaireAnswers' : QuestionnaireAnswers,
  'xpToNextLevel' : bigint,
  'avatarChoice' : string,
  'unlockedSkills' : Array<string>,
  'lastMissionCompletionTime' : CooldownArray,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDailyTask' : ActorMethod<[DailyTask], undefined>,
  'addMission' : ActorMethod<[Mission], undefined>,
  'addSkill' : ActorMethod<[Skill], undefined>,
  'addXp' : ActorMethod<[bigint], UserProfile>,
  'allocateStats' : ActorMethod<[Array<[bigint, bigint]>], UserProfile>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeMission' : ActorMethod<[string], UserProfile>,
  'completeUserMission' : ActorMethod<[string], UserProfile>,
  'createCustomTask' : ActorMethod<[string, bigint, bigint], undefined>,
  'createUserMission' : ActorMethod<[string, string, bigint, bigint], string>,
  'deleteAccount' : ActorMethod<[], undefined>,
  'deleteCustomTask' : ActorMethod<[string], undefined>,
  'deleteUserMission' : ActorMethod<[string], undefined>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCheatItems' : ActorMethod<[], Array<CheatItem>>,
  'getCustomTasks' : ActorMethod<[], Array<CustomTaskWithStatus>>,
  'getDailyTaskRecommendations' : ActorMethod<[], DailyTaskRecommendation>,
  'getDamage' : ActorMethod<[Array<bigint>], DamageResult>,
  'getDirectionFromCoordinates' : ActorMethod<
    [[bigint, bigint], [bigint, bigint]],
    [string, string]
  >,
  'getDisciplineSkill' : ActorMethod<[string], [] | [DisciplineSkill]>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getMission' : ActorMethod<[string], [] | [Mission]>,
  'getMobStats' : ActorMethod<[bigint, bigint, bigint], StatArray>,
  'getQuestionnaireAnswers' : ActorMethod<[], [] | [QuestionnaireAnswers]>,
  'getSkill' : ActorMethod<[string], [] | [Skill]>,
  'getStartingStats' : ActorMethod<[bigint, bigint, bigint], StatArray>,
  'getStatNames' : ActorMethod<[], StatNameArray>,
  'getStatValue' : ActorMethod<[StatArray, StatArray, bigint], [] | [bigint]>,
  'getUserCheatPurchasesToday' : ActorMethod<[], Array<[string, bigint]>>,
  'getUserCustomTasks' : ActorMethod<[Principal], Array<CustomTaskWithStatus>>,
  'getUserMission' : ActorMethod<[string], [] | [UserMission]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeProfile' : ActorMethod<[string], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllMobTypes' : ActorMethod<[], Array<[bigint, string]>>,
  'listAllMobs' : ActorMethod<[], Array<Mob>>,
  'listDisciplineSkills' : ActorMethod<[], Array<DisciplineSkill>>,
  'listMissions' : ActorMethod<[], Array<Mission>>,
  'listSkills' : ActorMethod<[], Array<Skill>>,
  'listUserMissions' : ActorMethod<[], Array<UserMission>>,
  'markDailyTaskCompleted' : ActorMethod<[string], undefined>,
  'purchaseCheat' : ActorMethod<[string], PurchaseResult>,
  'rollDie' : ActorMethod<[bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitQuestionnaireAnswers' : ActorMethod<[QuestionnaireAnswers], undefined>,
  'toggleCustomTaskCompletion' : ActorMethod<[string, boolean], undefined>,
  'unlockSkill' : ActorMethod<[string], UserProfile>,
  'updateUsername' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];