/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CooldownArray = Array<[string, Time]>;
export interface DamageResult { 'damage' : bigint, 'stats' : Array<bigint> }
export interface Mission {
  'id' : string,
  'missionType' : { 'repeatable' : null } |
    { 'daily' : null },
  'xpReward' : bigint,
  'name' : string,
  'description' : string,
  'coinReward' : bigint,
  'requirements' : MissionRequirements,
}
export interface MissionRequirements { 'minLevel' : bigint }
export interface Mob {
  'name' : string,
  'level' : bigint,
  'typeIndex' : bigint,
  'stats' : StatArray,
}
export interface Skill {
  'id' : string,
  'name' : string,
  'description' : string,
  'requirements' : SkillRequirements,
}
export interface SkillRequirements {
  'minLevel' : bigint,
  'minStats' : Array<[bigint, bigint]>,
}
export type StatArray = Array<bigint>;
export type StatNameArray = Array<string>;
export type Time = bigint;
export interface UserProfile {
  'xp' : bigint,
  'nickname' : string,
  'inventory' : Array<string>,
  'coins' : bigint,
  'unspentStatPoints' : bigint,
  'completedMissions' : Array<string>,
  'level' : bigint,
  'stats' : StatArray,
  'xpToNextLevel' : bigint,
  'unlockedSkills' : Array<string>,
  'lastMissionCompletionTime' : CooldownArray,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMission' : ActorMethod<[Mission], undefined>,
  'addSkill' : ActorMethod<[Skill], undefined>,
  'addXp' : ActorMethod<[bigint], UserProfile>,
  'allocateStats' : ActorMethod<[Array<[bigint, bigint]>], UserProfile>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeMission' : ActorMethod<[string], UserProfile>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDamage' : ActorMethod<[Array<bigint>], DamageResult>,
  'getDirectionFromCoordinates' : ActorMethod<
    [[bigint, bigint], [bigint, bigint]],
    [string, string]
  >,
  'getMission' : ActorMethod<[string], [] | [Mission]>,
  'getMobStats' : ActorMethod<[bigint, bigint, bigint], StatArray>,
  'getSkill' : ActorMethod<[string], [] | [Skill]>,
  'getStartingStats' : ActorMethod<[bigint, bigint, bigint], StatArray>,
  'getStatNames' : ActorMethod<[], StatNameArray>,
  'getStatValue' : ActorMethod<[StatArray, StatArray, bigint], [] | [bigint]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeProfile' : ActorMethod<[string], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllMobTypes' : ActorMethod<[], Array<[bigint, string]>>,
  'listAllMobs' : ActorMethod<[], Array<Mob>>,
  'listMissions' : ActorMethod<[], Array<Mission>>,
  'listSkills' : ActorMethod<[], Array<Skill>>,
  'rollDie' : ActorMethod<[bigint], bigint>,
  'unlockSkill' : ActorMethod<[string], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];