/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MissionRequirements = IDL.Record({ 'minLevel' : IDL.Nat });
export const Mission = IDL.Record({
  'id' : IDL.Text,
  'missionType' : IDL.Variant({ 'repeatable' : IDL.Null, 'daily' : IDL.Null }),
  'xpReward' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'coinReward' : IDL.Nat,
  'requirements' : MissionRequirements,
});
export const SkillRequirements = IDL.Record({
  'minLevel' : IDL.Nat,
  'minStats' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Int)),
});
export const Skill = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'requirements' : SkillRequirements,
});
export const StatArray = IDL.Vec(IDL.Int);
export const Time = IDL.Int;
export const CooldownArray = IDL.Vec(IDL.Tuple(IDL.Text, Time));
export const UserProfile = IDL.Record({
  'xp' : IDL.Nat,
  'nickname' : IDL.Text,
  'inventory' : IDL.Vec(IDL.Text),
  'coins' : IDL.Nat,
  'unspentStatPoints' : IDL.Nat,
  'completedMissions' : IDL.Vec(IDL.Text),
  'level' : IDL.Nat,
  'stats' : StatArray,
  'xpToNextLevel' : IDL.Nat,
  'unlockedSkills' : IDL.Vec(IDL.Text),
  'lastMissionCompletionTime' : CooldownArray,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DamageResult = IDL.Record({
  'damage' : IDL.Nat,
  'stats' : IDL.Vec(IDL.Int),
});
export const StatNameArray = IDL.Vec(IDL.Text);
export const Mob = IDL.Record({
  'name' : IDL.Text,
  'level' : IDL.Nat,
  'typeIndex' : IDL.Nat,
  'stats' : StatArray,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMission' : IDL.Func([Mission], [], []),
  'addSkill' : IDL.Func([Skill], [], []),
  'addXp' : IDL.Func([IDL.Nat], [UserProfile], []),
  'allocateStats' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Int))],
      [UserProfile],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeMission' : IDL.Func([IDL.Text], [UserProfile], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDamage' : IDL.Func([IDL.Vec(IDL.Int)], [DamageResult], []),
  'getDirectionFromCoordinates' : IDL.Func(
      [IDL.Tuple(IDL.Nat, IDL.Nat), IDL.Tuple(IDL.Nat, IDL.Nat)],
      [IDL.Text, IDL.Text],
      [],
    ),
  'getMission' : IDL.Func([IDL.Text], [IDL.Opt(Mission)], []),
  'getMobStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Int], [StatArray], []),
  'getSkill' : IDL.Func([IDL.Text], [IDL.Opt(Skill)], []),
  'getStartingStats' : IDL.Func([IDL.Int, IDL.Int, IDL.Int], [StatArray], []),
  'getStatNames' : IDL.Func([], [StatNameArray], ['query']),
  'getStatValue' : IDL.Func(
      [StatArray, StatArray, IDL.Nat],
      [IDL.Opt(IDL.Int)],
      [],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], []),
  'initializeProfile' : IDL.Func([IDL.Text], [UserProfile], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllMobTypes' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'listAllMobs' : IDL.Func([], [IDL.Vec(Mob)], ['query']),
  'listMissions' : IDL.Func([], [IDL.Vec(Mission)], []),
  'listSkills' : IDL.Func([], [IDL.Vec(Skill)], []),
  'rollDie' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'unlockSkill' : IDL.Func([IDL.Text], [UserProfile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MissionRequirements = IDL.Record({ 'minLevel' : IDL.Nat });
  const Mission = IDL.Record({
    'id' : IDL.Text,
    'missionType' : IDL.Variant({
      'repeatable' : IDL.Null,
      'daily' : IDL.Null,
    }),
    'xpReward' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'coinReward' : IDL.Nat,
    'requirements' : MissionRequirements,
  });
  const SkillRequirements = IDL.Record({
    'minLevel' : IDL.Nat,
    'minStats' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Int)),
  });
  const Skill = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'requirements' : SkillRequirements,
  });
  const StatArray = IDL.Vec(IDL.Int);
  const Time = IDL.Int;
  const CooldownArray = IDL.Vec(IDL.Tuple(IDL.Text, Time));
  const UserProfile = IDL.Record({
    'xp' : IDL.Nat,
    'nickname' : IDL.Text,
    'inventory' : IDL.Vec(IDL.Text),
    'coins' : IDL.Nat,
    'unspentStatPoints' : IDL.Nat,
    'completedMissions' : IDL.Vec(IDL.Text),
    'level' : IDL.Nat,
    'stats' : StatArray,
    'xpToNextLevel' : IDL.Nat,
    'unlockedSkills' : IDL.Vec(IDL.Text),
    'lastMissionCompletionTime' : CooldownArray,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DamageResult = IDL.Record({
    'damage' : IDL.Nat,
    'stats' : IDL.Vec(IDL.Int),
  });
  const StatNameArray = IDL.Vec(IDL.Text);
  const Mob = IDL.Record({
    'name' : IDL.Text,
    'level' : IDL.Nat,
    'typeIndex' : IDL.Nat,
    'stats' : StatArray,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMission' : IDL.Func([Mission], [], []),
    'addSkill' : IDL.Func([Skill], [], []),
    'addXp' : IDL.Func([IDL.Nat], [UserProfile], []),
    'allocateStats' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Int))],
        [UserProfile],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeMission' : IDL.Func([IDL.Text], [UserProfile], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDamage' : IDL.Func([IDL.Vec(IDL.Int)], [DamageResult], []),
    'getDirectionFromCoordinates' : IDL.Func(
        [IDL.Tuple(IDL.Nat, IDL.Nat), IDL.Tuple(IDL.Nat, IDL.Nat)],
        [IDL.Text, IDL.Text],
        [],
      ),
    'getMission' : IDL.Func([IDL.Text], [IDL.Opt(Mission)], []),
    'getMobStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Int], [StatArray], []),
    'getSkill' : IDL.Func([IDL.Text], [IDL.Opt(Skill)], []),
    'getStartingStats' : IDL.Func([IDL.Int, IDL.Int, IDL.Int], [StatArray], []),
    'getStatNames' : IDL.Func([], [StatNameArray], ['query']),
    'getStatValue' : IDL.Func(
        [StatArray, StatArray, IDL.Nat],
        [IDL.Opt(IDL.Int)],
        [],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], []),
    'initializeProfile' : IDL.Func([IDL.Text], [UserProfile], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllMobTypes' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'listAllMobs' : IDL.Func([], [IDL.Vec(Mob)], ['query']),
    'listMissions' : IDL.Func([], [IDL.Vec(Mission)], []),
    'listSkills' : IDL.Func([], [IDL.Vec(Skill)], []),
    'rollDie' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'unlockSkill' : IDL.Func([IDL.Text], [UserProfile], []),
  });
};

export const init = ({ IDL }) => { return []; };