export const COPY = {
  app: {
    name: 'CRYONEX',
    tagline: 'Advanced progression tracking system',
  },
  auth: {
    signIn: 'Initialize',
    signOut: 'Disconnect',
    connecting: 'Connecting...',
  },
  profileSetup: {
    welcomeTitle: 'Welcome to CRYONEX',
    welcomeDescription: 'Initialize your profile to begin tracking your progression through the system.',
    identityNote: 'Your profile is securely linked to your authentication identity.',
    nameLabel: 'Enter Your Name',
    namePlaceholder: 'Enter your name',
    beginButton: 'Initialize System',
    creatingProfile: 'Initializing...',
  },
  personalization: {
    title: 'Personalize Your Experience',
    description: 'Answer these questions to customize CRYONEX for your playstyle and preferences.',
    questionLabel: 'Question',
    of: 'of',
    next: 'Next',
    previous: 'Previous',
    submit: 'Complete Setup',
    submitting: 'Saving...',
    questions: [
      {
        question: 'What is your preferred playstyle?',
        options: [
          'Combat-focused: I love engaging in battles and defeating enemies',
          'Exploration: I enjoy discovering new areas and uncovering secrets',
          'Strategic: I prefer planning and optimizing my approach',
          'Balanced: I like a mix of all playstyles',
        ],
      },
      {
        question: 'Which mission types do you prefer?',
        options: [
          'Daily challenges: I like focused, time-limited objectives',
          'Repeatable grinds: I prefer missions I can complete multiple times',
          'Both equally: I enjoy variety in my mission selection',
          'Story-driven: I prefer missions with narrative depth',
        ],
      },
      {
        question: 'What stat priority interests you most?',
        options: [
          'Strength: Raw power and physical damage',
          'Agility: Speed and evasion capabilities',
          'Intelligence: Strategic advantages and skill effectiveness',
          'Balanced: Even distribution across all stats',
        ],
      },
      {
        question: 'Which skill category appeals to you?',
        options: [
          'Offensive: Damage-dealing and aggressive abilities',
          'Defensive: Protection and survivability skills',
          'Utility: Support and enhancement capabilities',
          'Mixed: A combination of all skill types',
        ],
      },
      {
        question: 'What is your primary game goal?',
        options: [
          'Level quickly: Reach maximum level as fast as possible',
          'Collect items: Build a comprehensive inventory',
          'Master skills: Unlock and perfect all available skills',
          'Explore everything: Experience all content the game offers',
        ],
      },
    ],
  },
  dashboard: {
    title: 'Command Center',
    welcomeBack: 'System online',
    continueJourney: 'Continue your progression',
    level: 'Level',
    experience: 'Experience',
    coins: 'Credits',
    unspentPoints: 'Unallocated Points',
    currentRank: 'Current level',
    toNextLevel: 'to next level',
    currencyBalance: 'Credit balance',
    availableToAllocate: 'Available to allocate',
    levelProgress: 'Level Progress',
    progressionSummary: 'System Status',
    missionsCompleted: 'Missions Completed',
    skillsUnlocked: 'Skills Unlocked',
    inventoryItems: 'Inventory Items',
  },
  missions: {
    title: 'Mission Log',
    subtitle: 'Complete missions to earn experience and credits',
    description: 'Complete missions to earn experience and credits',
    daily: 'Daily',
    repeatable: 'Repeatable',
    dailyMissions: 'Daily Operations',
    dailyDescription: 'Available once per cycle',
    repeatableMissions: 'Repeatable Operations',
    repeatableDescription: 'Complete as many times as needed',
    completeMission: 'Execute Mission',
    completing: 'Executing...',
    complete: 'Complete',
    completed: 'Completed',
    completedToday: 'Completed This Cycle',
    locked: 'Locked',
    requiredLevel: 'Required Level',
    noMissions: 'No missions available in the system',
    xp: 'XP',
    coins: 'Credits',
  },
  missionLog: {
    title: 'Mission Log History',
    description: 'Track your daily progress and achievements',
    emptyState: 'No activity logged yet today. Complete tasks and missions to see your daily progress here.',
    todayProgress: 'Today\'s Progress',
    overallStats: 'Overall Statistics',
    tasksCompleted: 'Tasks Completed',
    missionsCompleted: 'Missions Completed',
    xpEarned: 'XP Earned',
    coinsEarned: 'Coins Earned',
  },
  stats: {
    title: 'Attributes',
    subtitle: 'Allocate points to enhance your capabilities',
    description: 'Allocate points to enhance your capabilities',
    availablePoints: 'Available Points',
    pointsRemaining: 'Points Remaining',
    current: 'Current',
    reset: 'Reset',
    allocate: 'Allocate',
    allocating: 'Allocating...',
    confirmAllocation: 'Confirm Allocation',
    points: 'Points',
    pendingAllocation: 'pending allocation',
    loading: 'Loading stats...',
  },
  skills: {
    title: 'Skill Matrix',
    subtitle: 'Unlock advanced capabilities by meeting requirements',
    description: 'Unlock advanced capabilities by meeting requirements',
    unlocked: 'Active',
    locked: 'Locked',
    requirements: 'Requirements',
    requiresLevel: 'Requires Level',
    requiresStats: 'Required Stats',
    unlockSkill: 'Unlock Skill',
    unlock: 'Unlock',
    unlocking: 'Unlocking...',
    alreadyUnlocked: 'Already Active',
    requirementsNotMet: 'Requirements Not Met',
    noSkills: 'No skills available in the system',
    categories: {
      all: 'All Skills',
      physical: 'Physical',
      mental: 'Mental',
      productivity: 'Productivity',
      social: 'Social',
      creative: 'Creative',
      financial: 'Financial',
      health: 'Health',
      learning: 'Learning',
      personal: 'Personal Care',
      general: 'General',
    },
  },
  profile: {
    title: 'Profile & Settings',
    description: 'Manage your operator profile and system preferences',
    profileInformation: 'Operator Information',
    name: 'Operator ID',
    progressSummary: 'Progress Summary',
    accountActions: 'System Actions',
    clearCache: 'Clear Local Cache',
    signOut: 'Disconnect',
  },
  customTasks: {
    title: 'Custom Tasks',
    description: 'Create and manage your own personalized daily tasks with custom point values',
    createTaskTitle: 'Create New Task',
    createTaskDescription: 'Define a custom task with a title and point value',
    taskTitleLabel: 'Task Title',
    taskTitlePlaceholder: 'Enter task description',
    pointsLabel: 'XP Point Value',
    pointsRange: '(1-100 points)',
    attributePointsLabel: 'Attribute Points',
    attributePointsRange: '(1-10 points)',
    createButton: 'Create Task',
    creating: 'Creating...',
    yourTasks: 'Your Custom Tasks',
    activeTasks: 'Active Tasks',
    completedTasks: 'Completed Tasks',
    noTasks: 'No custom tasks yet. Create your first task above!',
    errorLoading: 'Failed to load custom tasks',
    xpPoints: 'XP',
    attributePoints: 'AP',
    complete: 'Complete',
    completing: 'Completing...',
    markIncomplete: 'Mark Incomplete',
    unmarking: 'Updating...',
  },
  customMissions: {
    title: 'Custom Missions',
    formTitle: 'Create Custom Mission',
    formDescription: 'Design your own mission with custom rewards and requirements',
    titleLabel: 'Mission Title',
    titlePlaceholder: 'Enter mission title',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'Describe the mission objective',
    xpRewardLabel: 'XP Reward',
    coinRewardLabel: 'Gold Reward',
    minLevelLabel: 'Minimum Level',
    createButton: 'Create Mission',
    creating: 'Creating...',
    cancelButton: 'Cancel',
    cancel: 'Cancel',
    delete: 'Delete',
    sectionTitle: 'Custom Missions',
    sectionDescription: 'Your personally created missions',
    createNewSection: 'Create New Mission',
    showForm: 'Show Creation Form',
    hideForm: 'Hide Creation Form',
    activeMissions: 'Active Missions',
    completedMissions: 'Completed Missions',
    emptyState: 'No custom missions yet. Create your first mission above!',
    noMissions: 'No custom missions yet. Create your first mission above!',
    completeButton: 'Complete Mission',
    deleteButton: 'Delete',
    deleteConfirmTitle: 'Delete Custom Mission?',
    deleteConfirmMessage: 'This action cannot be undone. The mission will be permanently deleted.',
    completedSection: 'Completed Custom Missions',
    custom: 'Custom',
    customBadge: 'Custom',
    xpLabel: 'XP',
    goldLabel: 'Gold',
    completed: 'Completed',
    validation: {
      titleRequired: 'Title is required',
      titleTooLong: 'Title must be 100 characters or less',
      descriptionRequired: 'Description is required',
      descriptionTooLong: 'Description must be 500 characters or less',
      xpRewardRange: 'XP reward must be between 10 and 500',
      coinRewardRange: 'Gold reward must be between 10 and 500',
      minLevelRange: 'Minimum level must be between 1 and 50',
    },
  },
  landing: {
    hero: 'Enter CRYONEX',
    description: 'Advanced progression tracking system with real-time mission management, skill unlocking, and attribute allocation.',
    authNote: 'Sign in with Google or other authentication providers to begin your journey.',
    getStarted: 'Initialize System',
    feature1Title: 'Mission Log',
    feature1Description: 'Track and complete daily and repeatable missions',
    feature2Title: 'Attributes',
    feature2Description: 'Allocate points to enhance your capabilities',
    feature3Title: 'Skill Matrix',
    feature3Description: 'Unlock advanced abilities as you progress',
    features: {
      title: 'System Features',
      missions: {
        title: 'Mission Log',
        description: 'Track and complete daily and repeatable missions',
      },
      stats: {
        title: 'Attributes',
        description: 'Allocate points to enhance your capabilities',
      },
      skills: {
        title: 'Skill Matrix',
        description: 'Unlock advanced abilities as you progress',
      },
      profile: {
        title: 'Profile System',
        description: 'Monitor your progression and achievements',
      },
    },
  },
};
