export const COPY = {
  app: {
    name: 'CRYONEX',
    tagline: 'Advanced progression tracking system',
  },
  auth: {
    signIn: 'Initialize',
    signOut: 'Disconnect',
    connecting: 'Connecting...',
  },
  profileSetup: {
    welcomeTitle: 'Welcome to CRYONEX',
    welcomeDescription: 'Initialize your profile to begin tracking your progression through the system.',
    identityNote: 'Your profile is securely linked to your authentication identity.',
    nameLabel: 'Operator ID',
    namePlaceholder: 'Enter your operator ID',
    beginButton: 'Initialize System',
    creatingProfile: 'Initializing...',
  },
  dashboard: {
    title: 'Command Center',
    welcomeBack: 'System online',
    continueJourney: 'Continue your progression',
    level: 'Level',
    experience: 'Experience',
    coins: 'Credits',
    unspentPoints: 'Unallocated Points',
    currentRank: 'Current level',
    toNextLevel: 'to next level',
    currencyBalance: 'Credit balance',
    availableToAllocate: 'Available to allocate',
    levelProgress: 'Level Progress',
    progressionSummary: 'System Status',
    missionsCompleted: 'Missions Completed',
    skillsUnlocked: 'Skills Unlocked',
    inventoryItems: 'Inventory Items',
  },
  missions: {
    title: 'Mission Log',
    description: 'Complete missions to earn experience and credits',
    daily: 'Daily',
    repeatable: 'Repeatable',
    dailyMissions: 'Daily Operations',
    dailyDescription: 'Available once per cycle',
    repeatableMissions: 'Repeatable Operations',
    repeatableDescription: 'Complete as many times as needed',
    completeMission: 'Execute Mission',
    completing: 'Executing...',
    completedToday: 'Completed This Cycle',
    locked: 'Locked',
    requiredLevel: 'Required Level',
    noMissions: 'No missions available in the system',
  },
  stats: {
    title: 'Attributes',
    description: 'Allocate points to enhance your capabilities',
    availablePoints: 'Available Points',
    current: 'Current',
    reset: 'Reset',
    allocate: 'Allocate',
    allocating: 'Allocating...',
    points: 'Points',
    pendingAllocation: 'pending allocation',
  },
  skills: {
    title: 'Skill Matrix',
    description: 'Unlock advanced capabilities by meeting requirements',
    unlocked: 'Active',
    locked: 'Locked',
    requirements: 'Requirements',
    unlockSkill: 'Unlock Skill',
    unlocking: 'Unlocking...',
    alreadyUnlocked: 'Already Active',
    requirementsNotMet: 'Requirements Not Met',
    noSkills: 'No skills available in the system',
  },
  profile: {
    title: 'Profile & Settings',
    description: 'Manage your operator profile and system preferences',
    profileInformation: 'Operator Information',
    name: 'Operator ID',
    progressSummary: 'Progress Summary',
    accountActions: 'System Actions',
    clearCache: 'Clear Local Cache',
    signOut: 'Disconnect',
  },
  landing: {
    hero: 'Enter CRYONEX',
    description: 'Advanced progression tracking system with real-time mission management, skill unlocking, and attribute allocation.',
    authNote: 'Sign in with Google or other authentication methods through Internet Identity.',
    feature1Title: 'Mission Operations',
    feature1Description: 'Execute daily and repeatable missions to earn experience and credits.',
    feature2Title: 'Level Progression',
    feature2Description: 'Gain experience, advance levels, and allocate attribute points to optimize your build.',
    feature3Title: 'Skill Matrix',
    feature3Description: 'Meet requirements and unlock advanced skills to enhance your capabilities.',
  },
};
