/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type StatArray = Array<bigint>;
export interface DailyTaskRecommendation {
    incomplete: Array<DailyTask>;
    completed: Array<DailyTask>;
}
export interface Mob {
    name: string;
    level: bigint;
    typeIndex: bigint;
    stats: StatArray;
}
export type Time = bigint;
export interface SkillRequirements {
    minLevel: bigint;
    minStats: Array<[bigint, bigint]>;
}
export type StatNameArray = Array<string>;
export interface DamageResult {
    damage: bigint;
    stats: Array<bigint>;
}
export type CooldownArray = Array<[string, Time]>;
export interface CustomTaskWithStatus {
    id: string;
    title: string;
    completed: boolean;
    attributePoints: bigint;
    points: bigint;
}
export interface Skill {
    id: string;
    name: string;
    description: string;
    requirements: SkillRequirements;
}
export type QuestionnaireAnswers = Array<string>;
export interface DailyTask {
    id: string;
    xpReward: bigint;
    description: string;
    coinReward: bigint;
}
export interface UserMission {
    id: string;
    missionType: Variant_repeatable_daily;
    xpReward: bigint;
    name: string;
    createdBy: Principal;
    description: string;
    coinReward: bigint;
}
export interface Mission {
    id: string;
    missionType: Variant_repeatable_daily;
    xpReward: bigint;
    name: string;
    description: string;
    coinReward: bigint;
}
export interface UserProfile {
    xp: bigint;
    credits: bigint;
    nickname: string;
    inventory: Array<string>;
    coins: bigint;
    unspentStatPoints: bigint;
    completedMissions: Array<string>;
    completedDailyTasks: Array<string>;
    level: bigint;
    stats: StatArray;
    questionnaireAnswers: QuestionnaireAnswers;
    xpToNextLevel: bigint;
    unlockedSkills: Array<string>;
    lastMissionCompletionTime: CooldownArray;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_repeatable_daily {
    repeatable = "repeatable",
    daily = "daily"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDailyTask(task: DailyTask): Promise<void>;
    addMission(mission: Mission): Promise<void>;
    addSkill(skill: Skill): Promise<void>;
    addXp(amount: bigint): Promise<UserProfile>;
    allocateStats(statAllocations: Array<[bigint, bigint]>): Promise<UserProfile>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeMission(missionId: string): Promise<UserProfile>;
    completeUserMission(missionId: string): Promise<UserProfile>;
    createCustomTask(title: string, points: bigint, attributePoints: bigint): Promise<void>;
    createUserMission(title: string, description: string, xpReward: bigint, coinReward: bigint): Promise<string>;
    deleteAccount(): Promise<void>;
    deleteCustomTask(taskId: string): Promise<void>;
    deleteUserMission(missionId: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomTasks(): Promise<Array<CustomTaskWithStatus>>;
    getDailyTaskRecommendations(): Promise<DailyTaskRecommendation>;
    getDamage(damageStats: Array<bigint>): Promise<DamageResult>;
    getDirectionFromCoordinates(_currentPosition: [bigint, bigint], _targetPosition: [bigint, bigint]): Promise<[string, string]>;
    getMission(missionId: string): Promise<Mission | null>;
    getMobStats(_mobTypeIndex: bigint, _level: bigint, _rangeRadius: bigint): Promise<StatArray>;
    getQuestionnaireAnswers(): Promise<QuestionnaireAnswers | null>;
    getSkill(skillId: string): Promise<Skill | null>;
    getStartingStats(pointPool: bigint, _rangeMin: bigint, _rangeMax: bigint): Promise<StatArray>;
    getStatNames(): Promise<StatNameArray>;
    getStatValue(_basicStats: StatArray, multipliers: StatArray, _statIndex: bigint): Promise<bigint | null>;
    getUserCustomTasks(user: Principal): Promise<Array<CustomTaskWithStatus>>;
    getUserMission(missionId: string): Promise<UserMission | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeProfile(nickname: string): Promise<UserProfile>;
    isCallerAdmin(): Promise<boolean>;
    listAllMobTypes(): Promise<Array<[bigint, string]>>;
    listAllMobs(): Promise<Array<Mob>>;
    listMissions(): Promise<Array<Mission>>;
    listSkills(): Promise<Array<Skill>>;
    listUserMissions(): Promise<Array<UserMission>>;
    markDailyTaskCompleted(taskId: string): Promise<void>;
    rollDie(sides: bigint): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitQuestionnaireAnswers(answers: QuestionnaireAnswers): Promise<void>;
    toggleCustomTaskCompletion(taskId: string, completed: boolean): Promise<void>;
    unlockSkill(skillId: string): Promise<UserProfile>;
    updateUsername(newUsername: string): Promise<void>;
}
import type { Mission as _Mission, QuestionnaireAnswers as _QuestionnaireAnswers, Skill as _Skill, UserMission as _UserMission, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDailyTask(arg0: DailyTask): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDailyTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDailyTask(arg0);
            return result;
        }
    }
    async addMission(arg0: Mission): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMission(to_candid_Mission_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMission(to_candid_Mission_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSkill(arg0: Skill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSkill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSkill(arg0);
            return result;
        }
    }
    async addXp(arg0: bigint): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.addXp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addXp(arg0);
            return result;
        }
    }
    async allocateStats(arg0: Array<[bigint, bigint]>): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.allocateStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.allocateStats(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeMission(arg0: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.completeMission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeMission(arg0);
            return result;
        }
    }
    async completeUserMission(arg0: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.completeUserMission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeUserMission(arg0);
            return result;
        }
    }
    async createCustomTask(arg0: string, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomTask(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomTask(arg0, arg1, arg2);
            return result;
        }
    }
    async createUserMission(arg0: string, arg1: string, arg2: bigint, arg3: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserMission(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserMission(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteAccount(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAccount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAccount();
            return result;
        }
    }
    async deleteCustomTask(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomTask(arg0);
            return result;
        }
    }
    async deleteUserMission(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUserMission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUserMission(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomTasks(): Promise<Array<CustomTaskWithStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomTasks();
            return result;
        }
    }
    async getDailyTaskRecommendations(): Promise<DailyTaskRecommendation> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyTaskRecommendations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyTaskRecommendations();
            return result;
        }
    }
    async getDamage(arg0: Array<bigint>): Promise<DamageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getDamage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDamage(arg0);
            return result;
        }
    }
    async getDirectionFromCoordinates(arg0: [bigint, bigint], arg1: [bigint, bigint]): Promise<[string, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.getDirectionFromCoordinates(arg0, arg1);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDirectionFromCoordinates(arg0, arg1);
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getMission(arg0: string): Promise<Mission | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMission(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMission(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMobStats(arg0: bigint, arg1: bigint, arg2: bigint): Promise<StatArray> {
        if (this.processError) {
            try {
                const result = await this.actor.getMobStats(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMobStats(arg0, arg1, arg2);
            return result;
        }
    }
    async getQuestionnaireAnswers(): Promise<QuestionnaireAnswers | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionnaireAnswers();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionnaireAnswers();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSkill(arg0: string): Promise<Skill | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkill(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkill(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStartingStats(arg0: bigint, arg1: bigint, arg2: bigint): Promise<StatArray> {
        if (this.processError) {
            try {
                const result = await this.actor.getStartingStats(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStartingStats(arg0, arg1, arg2);
            return result;
        }
    }
    async getStatNames(): Promise<StatNameArray> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatNames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatNames();
            return result;
        }
    }
    async getStatValue(arg0: StatArray, arg1: StatArray, arg2: bigint): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatValue(arg0, arg1, arg2);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatValue(arg0, arg1, arg2);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserCustomTasks(arg0: Principal): Promise<Array<CustomTaskWithStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCustomTasks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCustomTasks(arg0);
            return result;
        }
    }
    async getUserMission(arg0: string): Promise<UserMission | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMission(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMission(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeProfile(arg0: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeProfile(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllMobTypes(): Promise<Array<[bigint, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllMobTypes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllMobTypes();
            return result;
        }
    }
    async listAllMobs(): Promise<Array<Mob>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllMobs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllMobs();
            return result;
        }
    }
    async listMissions(): Promise<Array<Mission>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMissions();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMissions();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSkills(): Promise<Array<Skill>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSkills();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSkills();
            return result;
        }
    }
    async listUserMissions(): Promise<Array<UserMission>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUserMissions();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUserMissions();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async markDailyTaskCompleted(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markDailyTaskCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markDailyTaskCompleted(arg0);
            return result;
        }
    }
    async rollDie(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.rollDie(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rollDie(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitQuestionnaireAnswers(arg0: QuestionnaireAnswers): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuestionnaireAnswers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuestionnaireAnswers(arg0);
            return result;
        }
    }
    async toggleCustomTaskCompletion(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCustomTaskCompletion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCustomTaskCompletion(arg0, arg1);
            return result;
        }
    }
    async unlockSkill(arg0: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockSkill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockSkill(arg0);
            return result;
        }
    }
    async updateUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUsername(arg0);
            return result;
        }
    }
}
function from_candid_Mission_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mission): Mission {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserMission_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserMission): UserMission {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuestionnaireAnswers]): QuestionnaireAnswers | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Skill]): Skill | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserMission]): UserMission | null {
    return value.length === 0 ? null : from_candid_UserMission_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Mission]): Mission | null {
    return value.length === 0 ? null : from_candid_Mission_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    missionType: {
        repeatable: null;
    } | {
        daily: null;
    };
    xpReward: bigint;
    name: string;
    description: string;
    coinReward: bigint;
}): {
    id: string;
    missionType: Variant_repeatable_daily;
    xpReward: bigint;
    name: string;
    description: string;
    coinReward: bigint;
} {
    return {
        id: value.id,
        missionType: from_candid_variant_n12(_uploadFile, _downloadFile, value.missionType),
        xpReward: value.xpReward,
        name: value.name,
        description: value.description,
        coinReward: value.coinReward
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    missionType: {
        repeatable: null;
    } | {
        daily: null;
    };
    xpReward: bigint;
    name: string;
    createdBy: Principal;
    description: string;
    coinReward: bigint;
}): {
    id: string;
    missionType: Variant_repeatable_daily;
    xpReward: bigint;
    name: string;
    createdBy: Principal;
    description: string;
    coinReward: bigint;
} {
    return {
        id: value.id,
        missionType: from_candid_variant_n12(_uploadFile, _downloadFile, value.missionType),
        xpReward: value.xpReward,
        name: value.name,
        createdBy: value.createdBy,
        description: value.description,
        coinReward: value.coinReward
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    repeatable: null;
} | {
    daily: null;
}): Variant_repeatable_daily {
    return "repeatable" in value ? Variant_repeatable_daily.repeatable : "daily" in value ? Variant_repeatable_daily.daily : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Mission>): Array<Mission> {
    return value.map((x)=>from_candid_Mission_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserMission>): Array<UserMission> {
    return value.map((x)=>from_candid_UserMission_n17(_uploadFile, _downloadFile, x));
}
function to_candid_Mission_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mission): _Mission {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    missionType: Variant_repeatable_daily;
    xpReward: bigint;
    name: string;
    description: string;
    coinReward: bigint;
}): {
    id: string;
    missionType: {
        repeatable: null;
    } | {
        daily: null;
    };
    xpReward: bigint;
    name: string;
    description: string;
    coinReward: bigint;
} {
    return {
        id: value.id,
        missionType: to_candid_variant_n3(_uploadFile, _downloadFile, value.missionType),
        xpReward: value.xpReward,
        name: value.name,
        description: value.description,
        coinReward: value.coinReward
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_repeatable_daily): {
    repeatable: null;
} | {
    daily: null;
} {
    return value == Variant_repeatable_daily.repeatable ? {
        repeatable: null
    } : value == Variant_repeatable_daily.daily ? {
        daily: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
